name: flutter_kurdish_localization
description: Flutter Central Kurdish Localization in easy steps, simple ways to localize and translate your app to Central Kurdish.
version: 1.1.2  # Increment version after changes
homepage: https://github.com/aminsamad/flutter_kurdish_localization

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0  # Keep only one (preferably the newer version)
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated to latest

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_kurdish_localization
        pluginClass: FlutterKurdishLocalizationPlugin
      ios:
        pluginClass: FlutterKurdishLocalizationPlugin
      linux:
        pluginClass: FlutterKurdishLocalizationPlugin
      macos:
        pluginClass: FlutterKurdishLocalizationPlugin
      windows:
        pluginClass: FlutterKurdishLocalizationPluginCApi
      web:
        pluginClass: FlutterKurdishLocalizationWeb
        fileName: flutter_kurdish_localization_web.dart
